spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_management
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: mailsenderforjava@gmail.com
    password: iltifceckjkwsohf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


logging:
  level:
    root: info
    com.example.studentmanagement: debug
  file:
    name: C:\\Users\\Hakob\\IdeaProjects\\student-management\\logs\\student-management-%d{yyyy-MM-dd-HH-mm-ss}.%i.log
  logback:
    rollingpolicy:
      max-file-size: 10MB

student-management:
  picture:
    upload:
      directory: C:/Users/Hakob/IdeaProjects/student-management/pictures

